spring:
  rabbitmq:
          host: localhost
          port: 5672
          username: guest
          password: guest
server:
  port: 8885
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false